title: Testing the Just the Docs Template
description: Maybe eventually I'll get some real work done!
theme: just-the-docs

url: https://lkwhite.github.io/jtd-test

aux_links:
  GH Repository: https://github.com/lkwhite/jtd-test
