title: A tRNAseq guide
description: Notes on library prep and analysis
theme: just-the-docs

url: https://lkwhite.github.io
baseurl: /tRNAseq

aux_links:
  GH Repository: https://github.com/lkwhite/tRNAseq

permalink: pretty